name: FinGSetsForCAP
version: "2020.10-01"
license: "GPL-2.0-or-later"
date: 2020-10-16
description: |
    The elementary topos of (skeletal) finite G-sets

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2019.04.03"
      url: "https://homalg-project.github.io/CAP_project/CAP"
    - name: "Toposes"
      version: ">= 2018.09.17"
      url: "https://homalg-project.github.io/Toposes"

suggested-pkgs:
    - name: "FinSetsForCAP"
      version: ">= 2018.09.17"
      url: "https://homalg-project.github.io/FinSetsForCAP"

www: https://homalg-project.github.io/FinGSetsForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/FinGSetsForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/FinGSetsForCAP/releases/download/v2020.10-01/FinGSetsForCAP-2020.10-01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/FinGSetsForCAP/releases/download/v2020.10-01/FinGSetsForCAP-2020.10-01.zip

pdf: https://github.com/homalg-project/FinGSetsForCAP/releases/download/v2020.10-01/FinGSetsForCAP-2020.10-01.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BMZ20</span>]   <b class='BibAuthor'>Barakat, M., Mickisch, J. and Zickgraf, F.</b>,
     <i class='BibTitle'>FinGSetsForCAP, The elementary topos of (skeletal) finite G-sets,
             Version 2020.10-01</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/FinGSetsForCAP">https://homalg-project.github.io/FinGSetsForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ FinGSetsForCAP2020.10-01,
      author =           {Barakat, M. and Mickisch, J. and Zickgraf, F.},
      title =            {{FinGSetsForCAP},  The  elementary topos of (skeletal)
                          finite G-sets, {V}ersion 2020.10-01},
      month =            {Oct},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/FinGSetsForCAP}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{FinGSetsForCAP}}},
      printedkey =       {BMZ20}
    }

