name: FinGSetsForCAP
version: "2021.05-02"
license: "GPL-2.0-or-later"
date: 2022-05-16
description: |
    The elementary topos of (skeletal) finite G-sets

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

GAP: ">= 4.11.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2021.05-02"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "Toposes"
      version: ">= 2021.03-01"
      url: "https://homalg-project.github.io/pkg/Toposes"

suggested-pkgs:
    - name: "FinSetsForCAP"
      version: ">= 2022.05-01"
      url: "https://homalg-project.github.io/pkg/FinSetsForCAP"

www: https://homalg-project.github.io/pkg/FinGSetsForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/FinGSetsForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/FinGSetsForCAP/releases/download/v2021.05-02/FinGSetsForCAP-2021.05-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/FinGSetsForCAP/releases/download/v2021.05-02/FinGSetsForCAP-2021.05-02.zip

pdf: https://github.com/homalg-project/FinGSetsForCAP/releases/download/v2021.05-02/FinGSetsForCAP-2021.05-02.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BMZ22</span>]   <b class='BibAuthor'>Barakat, M., Mickisch, J. and Zickgraf, F.</b>,
     <i class='BibTitle'>FinGSetsForCAP, The elementary topos of (skeletal) finite G-sets,
             Version 2021.05-02</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/FinGSetsForCAP">https://homalg-project.github.io/pkg/FinGSetsForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ FinGSetsForCAP2021.05-02,
      author =           {Barakat, M. and Mickisch, J. and Zickgraf, F.},
      title =            {{FinGSetsForCAP},  The  elementary topos of (skeletal)
                          finite G-sets, {V}ersion 2021.05-02},
      month =            {May},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/FinGSetsForCAP}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{FinGSetsForCAP}}},
      printedkey =       {BMZ22}
    }

