name: FinGSetsForCAP
version: "2025.03-01"
license: "GPL-2.0-or-later"
date: 2025-03-16
description: |
    The elementary topos of (skeletal) finite G-sets

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

GAP: ">= 4.12.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2022.09-23"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "Toposes"
      version: ">= 2021.03-01"
      url: "https://homalg-project.github.io/pkg/Toposes"

suggested-pkgs:
    - name: "FinSetsForCAP"
      version: ">= 2022.05-01"
      url: "https://homalg-project.github.io/pkg/FinSetsForCAP"

www: https://homalg-project.github.io/pkg/FinGSetsForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/FinGSetsForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/FinGSetsForCAP/releases/download/v2025.03-01/FinGSetsForCAP-2025.03-01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/FinGSetsForCAP/releases/download/v2025.03-01/FinGSetsForCAP-2025.03-01.zip

pdf: https://github.com/homalg-project/FinGSetsForCAP/releases/download/v2025.03-01/FinGSetsForCAP-2025.03-01-manual.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BMZ16</span>]   <b class='BibAuthor'>Barakat, M., Mickisch, J. and Zickgraf, F.</b>,
     <i class='BibTitle'>FinGSetsForCAP, The elementary topos of (skeletal) finite G-sets,
             Version 2025.03-01</i>
     (<span class='BibYear'>3-16</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/FinGSetsForCAP">https://homalg-project.github.io/pkg/FinGSetsForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ FinGSetsForCAP,
      author =           {Barakat, M. and Mickisch, J. and Zickgraf, F.},
      title =            {{FinGSetsForCAP},  {The elementary topos of (skeletal)
                          finite      G\texttt{\symbol{45}}sets},      {V}ersion
                          2025.03\texttt{\symbol{45}}01},
      month =            {5\texttt{\symbol{45}}},
      year =             {3\texttt{\symbol{45}}16},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/FinGSetsForCAP}
                          {\texttt{https://homalg\texttt{\symbol{45}}project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{FinGSetsForCAP}}},
      printedkey =       {BMZ16}
    }

