name: FinGSetsForCAP
version: "2019.03.03"
license: "GPL-2.0-or-later"
date: 2019-03-03
description: |
    The elementary topos of (skeletal) finite G-sets

authors:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2019.04.03"
      url: "https://homalg-project.github.io/CAP_project/CAP"
    - name: "Toposes"
      version: ">= 2018.09.17"
      url: "https://homalg-project.github.io/Toposes"

suggested-pkgs:
    - name: "FinSetsForCAP"
      version: ">= 2018.09.17"
      url: "https://github.com/homalg-project/FinSetsForCAP"

www: https://github.com/homalg-project/FinGSetsForCAP
readme: README.md
packageinfo: https://raw.githubusercontent.com/homalg-project/FinGSetsForCAP/master/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/FinGSetsForCAP/releases/download/v2019.03.03/FinGSetsForCAP-2019.03.03.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BMZ19</span>]   <b class='BibAuthor'>Barakat, M., Mickisch, J. and Zickgraf, F.</b>,
     <i class='BibTitle'>FinGSetsForCAP, The elementary topos of (skeletal) finite G-sets,
             Version 2019.03.03</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://github.com/homalg-project/FinGSetsForCAP">https://github.com/homalg-project/FinGSetsForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ FinGSetsForCAP2019.03.03,
      author =           {Barakat, M. and Mickisch, J. and Zickgraf, F.},
      title =            {{FinGSetsForCAP}, The elementary topos of (skeletal) finite G-sets, {V}ersion 2019.03.03},
      month =            {Mar},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href    {https://github.com/homalg-project/FinGSetsForCAP}   {\texttt{https://github.com/}\discretionary   {}{}{}\texttt{homalg-project/}\discretionary
                          {}{}{}\texttt{FinGSetsForCAP}}},
      printedkey =       {BMZ19}
    }

